#!/bin/bash
# Ternary Reasoner — MLX local testing on Mac
# Requires: Apple Silicon Mac with native arm64 Python + MLX 0.22+
#   Install: /opt/homebrew/bin/pip3 install mlx sentencepiece numpy --break-system-packages
# Tuned for 16GB unified memory. For 32GB+ set MLX_EAGER_EVAL=0.

# Auto-detect arm64 Python (Homebrew) vs fallback to system python3
PYTHON_BIN=${PYTHON_BIN:-/opt/homebrew/bin/python3}
if [ ! -f "$PYTHON_BIN" ]; then
  PYTHON_BIN=python3
fi

# Quick smoke test defaults (small batch for Mac memory)
RUN_ID=${RUN_ID:-mlx_reasoner} \
DATA_PATH=${DATA_PATH:-../../../data/datasets/fineweb10B_sp1024} \
TOKENIZER_PATH=${TOKENIZER_PATH:-../../../data/tokenizers/fineweb_1024_bpe.model} \
VOCAB_SIZE=${VOCAB_SIZE:-1024} \
NUM_LAYERS=${NUM_LAYERS:-12} \
MODEL_DIM=${MODEL_DIM:-192} \
NUM_HEADS=${NUM_HEADS:-8} \
NUM_KV_HEADS=${NUM_KV_HEADS:-4} \
MLP_MULT=${MLP_MULT:-4} \
EMBED_DIM=${EMBED_DIM:-128} \
BITNET_GROUP_SIZE=${BITNET_GROUP_SIZE:-128} \
ACTIVATION=${ACTIVATION:-lrelu2} \
LEAKY_RELU_SLOPE=${LEAKY_RELU_SLOPE:-0.5} \
LOGIT_SOFTCAP=${LOGIT_SOFTCAP:-30} \
QK_GAIN_INIT=${QK_GAIN_INIT:-2.25} \
ROPE_BASE=${ROPE_BASE:-5000} \
TRAIN_BATCH_TOKENS=${TRAIN_BATCH_TOKENS:-32768} \
GRAD_ACCUM_STEPS=${GRAD_ACCUM_STEPS:-4} \
TRAIN_SEQ_LEN=${TRAIN_SEQ_LEN:-1024} \
MLX_MAX_MICROBATCH_TOKENS=${MLX_MAX_MICROBATCH_TOKENS:-8192} \
MLX_EAGER_EVAL=${MLX_EAGER_EVAL:-1} \
ITERATIONS=${ITERATIONS:-200} \
WARMUP_STEPS=${WARMUP_STEPS:-0} \
MAX_WALLCLOCK_SECONDS=${MAX_WALLCLOCK_SECONDS:-120} \
VAL_LOSS_EVERY=${VAL_LOSS_EVERY:-0} \
TRAIN_LOG_EVERY=${TRAIN_LOG_EVERY:-10} \
VAL_BATCH_SIZE=${VAL_BATCH_SIZE:-32768} \
MAX_VAL_TOKENS=${MAX_VAL_TOKENS:-65536} \
TIE_EMBEDDINGS=${TIE_EMBEDDINGS:-1} \
WARMDOWN_FRACTION=${WARMDOWN_FRACTION:-0.5} \
FEEDBACK_ENABLED=${FEEDBACK_ENABLED:-1} \
FEEDBACK_DIM=${FEEDBACK_DIM:-32} \
FEEDBACK_SKETCH_TOKENS=${FEEDBACK_SKETCH_TOKENS:-2} \
FEEDBACK_PASSES=${FEEDBACK_PASSES:-1} \
EVAL_FEEDBACK_PASSES=${EVAL_FEEDBACK_PASSES:-2} \
CAPSULE_ENABLED=${CAPSULE_ENABLED:-1} \
CAPSULE_NUM=${CAPSULE_NUM:-8} \
CAPSULE_DIM=${CAPSULE_DIM:-32} \
BIGRAM_HASH_ENABLED=${BIGRAM_HASH_ENABLED:-1} \
BIGRAM_HASH_BUCKETS=${BIGRAM_HASH_BUCKETS:-2048} \
BIGRAM_HASH_DIM=${BIGRAM_HASH_DIM:-64} \
VRL_ENABLED=${VRL_ENABLED:-1} \
VRL_START_LAYER=${VRL_START_LAYER:-10} \
LN_SCALE_DAMPING=${LN_SCALE_DAMPING:-1} \
PARTIAL_ROPE_DIMS=${PARTIAL_ROPE_DIMS:-16} \
XSA_START_LAYER=${XSA_START_LAYER:-8} \
EMA_ENABLED=${EMA_ENABLED:-0} \
GPTQ_LITE_ENABLED=${GPTQ_LITE_ENABLED:-1} \
TURBO_QUANT_KV=${TURBO_QUANT_KV:-1} \
TURBO_QUANT_TRAIN=${TURBO_QUANT_TRAIN:-0} \
MOE_ENABLED=${MOE_ENABLED:-0} \
MOE_NUM_EXPERTS=${MOE_NUM_EXPERTS:-8} \
MOE_TOP_K=${MOE_TOP_K:-2} \
MOE_ROUTER_AUX_LOSS_COEF=${MOE_ROUTER_AUX_LOSS_COEF:-0.01} \
TERNARY_NOISE_SCALE=${TERNARY_NOISE_SCALE:-0.0} \
STOCHASTIC_DEPTH_PROB=${STOCHASTIC_DEPTH_PROB:-0.0} \
CURRICULUM_ENABLED=${CURRICULUM_ENABLED:-0} \
CURRICULUM_PHASE1_FRAC=${CURRICULUM_PHASE1_FRAC:-0.05} \
CURRICULUM_PHASE2_FRAC=${CURRICULUM_PHASE2_FRAC:-0.20} \
CURRICULUM_PHASE3_FRAC=${CURRICULUM_PHASE3_FRAC:-1.0} \
CURRICULUM_PHASE4_FRAC=${CURRICULUM_PHASE4_FRAC:-1.0} \
CURRICULUM_PHASE5_FRAC=${CURRICULUM_PHASE5_FRAC:-1.0} \
CURRICULUM_PHASE1_SEQ=${CURRICULUM_PHASE1_SEQ:-64} \
CURRICULUM_PHASE2_SEQ=${CURRICULUM_PHASE2_SEQ:-256} \
CURRICULUM_PHASE3_SEQ=${CURRICULUM_PHASE3_SEQ:-512} \
CURRICULUM_PHASE4_SEQ=${CURRICULUM_PHASE4_SEQ:-1024} \
CURRICULUM_PHASE5_SEQ=${CURRICULUM_PHASE5_SEQ:-1024} \
SELF_DISTILL_KL_WEIGHT=${SELF_DISTILL_KL_WEIGHT:-0.0} \
EMA_EVAL_APPLY=${EMA_EVAL_APPLY:-0} \
FEEDBACK_EVERY=${FEEDBACK_EVERY:-2} \
KOOPMAN_RANK=${KOOPMAN_RANK:-2} \
KOOPMAN_LR=${KOOPMAN_LR:-0.01} \
MATRIX_LR=${MATRIX_LR:-0.025} \
SCALAR_LR=${SCALAR_LR:-0.025} \
TIED_EMBED_LR=${TIED_EMBED_LR:-0.035} \
MUON_MOMENTUM=${MUON_MOMENTUM:-0.95} \
MUON_BACKEND_STEPS=${MUON_BACKEND_STEPS:-5} \
MUON_MOMENTUM_WARMUP_STEPS=${MUON_MOMENTUM_WARMUP_STEPS:-1500} \
GRAD_CLIP_NORM=${GRAD_CLIP_NORM:-0.3} \
SEED=${SEED:-42} \
NGRAM_CACHE_ENABLED=${NGRAM_CACHE_ENABLED:-1} \
NGRAM_MAX_ORDER=${NGRAM_MAX_ORDER:-5} \
NGRAM_ALPHA_BASE=${NGRAM_ALPHA_BASE:-0.05} \
NGRAM_ALPHA_SCALE=${NGRAM_ALPHA_SCALE:-0.55} \
NGRAM_ENTROPY_CENTER=${NGRAM_ENTROPY_CENTER:-4.0} \
TTT_ENABLED=${TTT_ENABLED:-1} \
TTT_SCOPE=${TTT_SCOPE:-feedback} \
TTT_LR=${TTT_LR:-0.002} \
TTT_EPOCHS=${TTT_EPOCHS:-1} \
TTT_CHUNK_TOKENS=${TTT_CHUNK_TOKENS:-32768} \
TTT_MOMENTUM=${TTT_MOMENTUM:-0.9} \
TTT_BATCH_SEQS=${TTT_BATCH_SEQS:-32} \
TTT_GRAD_CLIP=${TTT_GRAD_CLIP:-1.0} \
SHARED_BLOCKS=${SHARED_BLOCKS:-0} \
ARCHITECTURE=${ARCHITECTURE:-transformer} \
KOOPMAN_STATE_DIM=${KOOPMAN_STATE_DIM:-128} \
KOOPMAN_MIXER_RANK=${KOOPMAN_MIXER_RANK:-4} \
KOOPMAN_CONV_KERNEL=${KOOPMAN_CONV_KERNEL:-4} \
KOOPMAN_DECAY_WINDOW=${KOOPMAN_DECAY_WINDOW:-32} \
"$PYTHON_BIN" -u train_gpt_mlx.py
