#!/usr/bin/env bash
set -euo pipefail

cd /workspace
mkdir -p /workspace/logs
COMPILE_LOG=/workspace/logs/fix_probe_moeb.compile.log
TRAIN_LOG=/workspace/logs/fix_probe_moeb.train.log

# 1) precompile
CUDA_VISIBLE_DEVICES=1 TOKENIZER_PATH=/workspace/data/tokenizers/fineweb_8192_bpe.model DATA_PATH=/workspace/data/datasets/fineweb10B_sp8192 \
VOCAB_SIZE=8192 NUM_HEADS=8 NUM_KV_HEADS=8 TRAIN_SEQ_LEN=1024 TRAIN_BATCH_TOKENS=4096 GRAD_ACCUM_STEPS=1 \
VAL_BATCH_SIZE=2048 VAL_MAX_TOKENS=4096 FAST_SMOKE=1 FAST_SMOKE_BATCHES=16 SLIDING_EVAL=0 TTT_ENABLED=0 NGRAM_CACHE_ENABLED=0 \
DDP_FIND_UNUSED_PARAMETERS=1 PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True TORCHINDUCTOR_COMPILE_THREADS=32 \
TORCHINDUCTOR_FX_GRAPH_CACHE=1 TORCHINDUCTOR_AUTOGRAD_CACHE=1 TORCHINDUCTOR_CACHE_DIR=/workspace/torch_cache TRITON_CACHE_DIR=/workspace/triton_cache \
TORCHDYNAMO_CACHE_SIZE_LIMIT=1024 \
MOE_ENABLED=1 MOE_NUM_EXPERTS=8 MOE_TOP_K=1 MOE_LAYER_FRAC=0.60 NUM_LAYERS=10 MODEL_DIM=384 MLP_MULT=4 SHARED_BLOCKS=0 \
COMPILE_MODE=max-autotune COMPILER_WARMUP_STEPS=1 PRECOMPILE_ONLY=1 SYNTHETIC_WARMUP=1 ITERATIONS=0 MAX_WALLCLOCK_SECONDS=20 \
python3 build_submission.py >/dev/null && python3 train_gpt.py >"$COMPILE_LOG" 2>&1 || true

# 2) short train with dense logging
CUDA_VISIBLE_DEVICES=1 TOKENIZER_PATH=/workspace/data/tokenizers/fineweb_8192_bpe.model DATA_PATH=/workspace/data/datasets/fineweb10B_sp8192 \
VOCAB_SIZE=8192 NUM_HEADS=8 NUM_KV_HEADS=8 TRAIN_SEQ_LEN=1024 TRAIN_BATCH_TOKENS=4096 GRAD_ACCUM_STEPS=1 \
VAL_BATCH_SIZE=2048 VAL_MAX_TOKENS=4096 FAST_SMOKE=1 FAST_SMOKE_BATCHES=16 SLIDING_EVAL=0 TTT_ENABLED=0 NGRAM_CACHE_ENABLED=0 \
DDP_FIND_UNUSED_PARAMETERS=1 PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True TORCHINDUCTOR_COMPILE_THREADS=32 \
TORCHINDUCTOR_FX_GRAPH_CACHE=1 TORCHINDUCTOR_AUTOGRAD_CACHE=1 TORCHINDUCTOR_CACHE_DIR=/workspace/torch_cache TRITON_CACHE_DIR=/workspace/triton_cache \
TORCHDYNAMO_CACHE_SIZE_LIMIT=1024 \
MOE_ENABLED=1 MOE_NUM_EXPERTS=8 MOE_TOP_K=1 MOE_LAYER_FRAC=0.60 NUM_LAYERS=10 MODEL_DIM=384 MLP_MULT=4 SHARED_BLOCKS=0 \
COMPILE_MODE=max-autotune COMPILER_WARMUP_STEPS=0 PRECOMPILE_ONLY=0 SYNTHETIC_WARMUP=0 ITERATIONS=100000 MAX_WALLCLOCK_SECONDS=30 \
TRAIN_LOG_EVERY=1 TRAIN_LOG_EVERY_FRACTION=0 \
python3 build_submission.py >/dev/null && python3 train_gpt.py >"$TRAIN_LOG" 2>&1 || true

echo "--- step lines (first 12) ---"
grep -E "step:[0-9]+/[0-9]+ loss:" "$TRAIN_LOG" | head -n 12 || true
echo "--- stop/final ---"
grep -E "stopping_early|final_evaluation:completed|final_ternary_roundtrip" "$TRAIN_LOG" || true
