worker_processes  1;
error_log  /Users/akhileshgogikar/parameter-golf/nginx_error.log;
pid        /Users/akhileshgogikar/parameter-golf/nginx.pid;

events {
    worker_connections  1024;
}

http {
    include       /opt/homebrew/etc/nginx/mime.types;
    default_type  application/octet-stream;

    sendfile        on;
    access_log      /Users/akhileshgogikar/parameter-golf/nginx_access.log;
    keepalive_timeout  65;

    server {
        listen       8080;
        server_name  localhost;

        location / {
            root   /Users/akhileshgogikar/parameter-golf/web;
            index  index.html index.htm;
        }

        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   html;
        }
    }
}
