#!/usr/bin/env bash
set -euo pipefail

cd "$(dirname "$0")"
mkdir -p logs

export CUDA_VISIBLE_DEVICES="${CUDA_VISIBLE_DEVICES:-0}"
export PYTORCH_CUDA_ALLOC_CONF="${PYTORCH_CUDA_ALLOC_CONF:-expandable_segments:True}"

export MODEL_FAMILY=compressed_ut
export TRAIN_STAGE=joint
export DATA_PATH="${DATA_PATH:-./data/datasets/fineweb10B_bytes}"
export RUN_ID="${RUN_ID:-h100_bootleg_joint_80m}"
export SEED="${SEED:-1337}"

# 80 H100-minutes on 1xH100, matching the rough hardware-minute budget of 8xH100 for 10 minutes.
export MAX_WALLCLOCK_SECONDS=4800
export ITERATIONS="${ITERATIONS:-1000000}"
export WARMUP_STEPS="${WARMUP_STEPS:-32}"
export WARMDOWN_ITERS="${WARMDOWN_ITERS:-220}"
export TRAIN_LOG_EVERY="${TRAIN_LOG_EVERY:-20}"
export VAL_LOSS_EVERY="${VAL_LOSS_EVERY:-300}"

export TRAIN_SEQ_LEN="${TRAIN_SEQ_LEN:-1536}"
export TRAIN_BATCH_TOKENS="${TRAIN_BATCH_TOKENS:-393216}"
export GRAD_ACCUM_STEPS="${GRAD_ACCUM_STEPS:-1}"

export MAX_VAL_TOKENS="${MAX_VAL_TOKENS:-262144}"
export FINAL_FULL_VAL="${FINAL_FULL_VAL:-0}"
export FINAL_MAX_VAL_TOKENS="${FINAL_MAX_VAL_TOKENS:-1048576}"
export EVAL_BATCH_SEQS="${EVAL_BATCH_SEQS:-16}"
export EVAL_STRIDE="${EVAL_STRIDE:-128}"

export VOCAB_SIZE=256
export PAD_ID=0
export BYTE_OFFSET=0
export BYTE_COUNT=256

export BYTE_DIM="${BYTE_DIM:-448}"
export MODEL_DIM="${MODEL_DIM:-1408}"
export NUM_HEADS="${NUM_HEADS:-8}"
export NUM_KV_HEADS="${NUM_KV_HEADS:-4}"
export MLP_MULT="${MLP_MULT:-4.0}"
export PARTIAL_ROPE_DIM="${PARTIAL_ROPE_DIM:-32}"
export BIGRAM_DIM="${BIGRAM_DIM:-128}"
export COMPRESS_STRIDE="${COMPRESS_STRIDE:-4}"
export UT_STEPS="${UT_STEPS:-5}"

export DECODER_DIM="${DECODER_DIM:-256}"
export DECODER_LAYERS="${DECODER_LAYERS:-1}"
export DECODER_HEADS="${DECODER_HEADS:-4}"
export DECODER_MLP_MULT="${DECODER_MLP_MULT:-4.0}"
export DECODER_BRIDGE_LAYERS="${DECODER_BRIDGE_LAYERS:-1}"

export PRED_DIM="${PRED_DIM:-896}"
export PRED_STEPS="${PRED_STEPS:-2}"
export PRED_HEADS="${PRED_HEADS:-4}"
export PRED_KV_HEADS="${PRED_KV_HEADS:-2}"
export PRED_MLP_MULT="${PRED_MLP_MULT:-2.0}"

export JEPA_WEIGHT="${JEPA_WEIGHT:-1.0}"
export JOINT_CE_WEIGHT="${JOINT_CE_WEIGHT:-0.5}"
export CE_AUX_WEIGHT="${CE_AUX_WEIGHT:-0.2}"
export SIGREG_WEIGHT="${SIGREG_WEIGHT:-0.01}"

export BOOTLEG_COMPRESS_WEIGHT="${BOOTLEG_COMPRESS_WEIGHT:-0.35}"
export BOOTLEG_MID_WEIGHT="${BOOTLEG_MID_WEIGHT:-0.7}"
export BOOTLEG_FINAL_WEIGHT="${BOOTLEG_FINAL_WEIGHT:-1.35}"
export TEACHER_EMA_DECAY="${TEACHER_EMA_DECAY:-0.998}"

export JOINT_CE_SCALE_START="${JOINT_CE_SCALE_START:-0.2}"
export JOINT_CE_SCALE_END="${JOINT_CE_SCALE_END:-1.0}"
export JOINT_CE_RAMP_START="${JOINT_CE_RAMP_START:-0.55}"
export JOINT_CE_RAMP_END="${JOINT_CE_RAMP_END:-0.9}"
export JOINT_JEPA_SCALE_START="${JOINT_JEPA_SCALE_START:-1.0}"
export JOINT_JEPA_SCALE_END="${JOINT_JEPA_SCALE_END:-0.2}"
export JOINT_JEPA_RAMP_START="${JOINT_JEPA_RAMP_START:-0.72}"
export JOINT_JEPA_RAMP_END="${JOINT_JEPA_RAMP_END:-0.97}"

export EMBED_LR="${EMBED_LR:-0.45}"
export MATRIX_LR="${MATRIX_LR:-0.02}"
export SCALAR_LR="${SCALAR_LR:-0.035}"
export GRAD_CLIP_NORM="${GRAD_CLIP_NORM:-0.3}"

export EXPORT_EMA_ENABLED="${EXPORT_EMA_ENABLED:-1}"
export EXPORT_EMA_DECAY="${EXPORT_EMA_DECAY:-0.998}"
export LATE_QAT_THRESHOLD="${LATE_QAT_THRESHOLD:-0.08}"
export INT6_ENABLED="${INT6_ENABLED:-1}"
export USE_ZSTD="${USE_ZSTD:-0}"

export TTT_ENABLED=0
export USE_COMPILE="${USE_COMPILE:-1}"

python3 train_gpt.py 2>&1 | tee "logs/${RUN_ID}.txt"
