from __future__ import annotations

from research.presets import DEFAULT_DATA_PATH, DEFAULT_TOKENIZER_PATH, Preset, RunScale


FRONTIER_CONTROL_BASE_ENV = {
    "DATA_PATH": DEFAULT_DATA_PATH,
    "TOKENIZER_PATH": DEFAULT_TOKENIZER_PATH,
    "VOCAB_SIZE": "1024",
    "ITERATIONS": "20000",
    "MAX_WALLCLOCK_SECONDS": "600",
    "TRAIN_LOG_EVERY": "100",
    "VAL_LOSS_EVERY": "4000",
    "TRAIN_BATCH_TOKENS": "786432",
    "TRAIN_SEQ_LEN": "2048",
    "EVAL_SEQ_LEN": "2048",
    "WARMUP_STEPS": "20",
    "WARMDOWN_ITERS": "3500",
    "MODEL_DIM": "512",
    "NUM_LAYERS": "11",
    "NUM_HEADS": "8",
    "NUM_KV_HEADS": "4",
    "MLP_MULT": "3.0",
    "TIE_EMBEDDINGS": "1",
    "MATRIX_LR": "0.025",
    "SCALAR_LR": "0.025",
    "TIED_EMBED_LR": "0.035",
    "MUON_MOMENTUM": "0.99",
    "MUON_MOMENTUM_WARMUP_START": "0.92",
    "MUON_MOMENTUM_WARMUP_STEPS": "1500",
    "MUON_WD": "0.04",
    "ADAM_WD": "0.04",
    "EVAL_STRIDE": "64",
    "SWA_ENABLED": "1",
    "SWA_EVERY": "50",
    "BIGRAM_VOCAB_SIZE": "1536",
    "BIGRAM_DIM": "128",
    "XSA_LAST_N": "4",
    "ROPE_DIMS": "16",
    "LN_SCALE": "1",
    "VE_ENABLED": "1",
    "VE_DIM": "128",
    "VE_LAYERS": "9,10",
    "GATED_ATTENTION": "0",
    "VALUE_RESIDUAL": "0",
    "ROTARY_FIX": "0",
    "TTT_ENABLED": "1",
    "TTT_LR": "0.002",
    "TTT_EPOCHS": "3",
    "TTT_CHUNK_TOKENS": "32768",
    "TTT_FREEZE_BLOCKS": "0",
    "TTT_MOMENTUM": "0.9",
    "TTT_BATCH_SEQS": "32",
    "TTT_GRAD_CLIP": "1.0",
    "CAUSAL_CACHE_MODE": "off",
    "CAUSAL_CACHE_MAX_ORDER": "7",
    "CAUSAL_CACHE_ALPHA": "0.40",
    "CAUSAL_CACHE_MIN_COUNT": "2",
    "CAUSAL_CACHE_BUCKETS": "4194304",
    "CAUSAL_CACHE_MIXING": "fixed",
    "CAUSAL_CACHE_COUNT_SMOOTHING": "4.0",
    "VAL_TOKEN_LIMIT": "0",
    "CHECKPOINT_EVERY": "0",
}


FRONTIER_GPTQ_BASE_ENV = {
    "DATA_PATH": DEFAULT_DATA_PATH,
    "TOKENIZER_PATH": DEFAULT_TOKENIZER_PATH,
    "VOCAB_SIZE": "1024",
    "ITERATIONS": "20000",
    "MAX_WALLCLOCK_SECONDS": "560",
    "TRAIN_LOG_EVERY": "100",
    "VAL_LOSS_EVERY": "4000",
    "TRAIN_BATCH_TOKENS": "786432",
    "TRAIN_SEQ_LEN": "2048",
    "EVAL_SEQ_LEN": "2048",
    "WARMUP_STEPS": "20",
    "WARMDOWN_ITERS": "4000",
    "MODEL_DIM": "512",
    "NUM_LAYERS": "11",
    "NUM_HEADS": "8",
    "NUM_KV_HEADS": "4",
    "MLP_MULT": "3.0",
    "TIE_EMBEDDINGS": "1",
    "MATRIX_LR": "0.025",
    "SCALAR_LR": "0.025",
    "TIED_EMBED_LR": "0.035",
    "MUON_MOMENTUM": "0.99",
    "MUON_MOMENTUM_WARMUP_START": "0.92",
    "MUON_MOMENTUM_WARMUP_STEPS": "1500",
    "MUON_WD": "0.04",
    "ADAM_WD": "0.04",
    "SWA_ENABLED": "1",
    "SWA_EVERY": "50",
    "SWA_EMA_BLEND": "0.5",
    "EVAL_STRIDE": "64",
    "BIGRAM_VOCAB_SIZE": "3072",
    "BIGRAM_DIM": "128",
    "XSA_LAST_N": "11",
    "ROPE_DIMS": "16",
    "LN_SCALE": "1",
    "VE_ENABLED": "1",
    "VE_DIM": "128",
    "VE_LAYERS": "9,10",
    "VRL": "1",
    "ROTARY_FIX": "0",
    "GPTQ_ENABLED": "1",
    "GPTQ_CALIB_BATCHES": "256",
    "GPTQ_BLOCK_SIZE": "128",
    "SELECTIVE_PRUNE_ENABLED": "1",
    "SELECTIVE_PRUNE_TARGET_MB": "15.90",
    "CAUSAL_CACHE_MODE": "off",
    "CAUSAL_CACHE_MAX_ORDER": "7",
    "CAUSAL_CACHE_ALPHA": "0.40",
    "CAUSAL_CACHE_MIN_COUNT": "2",
    "CAUSAL_CACHE_BUCKETS": "4194304",
    "CAUSAL_CACHE_MIXING": "fixed",
    "CAUSAL_CACHE_COUNT_SMOOTHING": "4.0",
    "TTT_ENABLED": "0",
    "TTT_LR": "0.0001",
    "TTT_EPOCHS": "3",
    "TTT_CHUNK_TOKENS": "131072",
    "TTT_FREEZE_BLOCKS": "9",
    "TTT_FREEZE_EMBEDDINGS": "0",
    "TTT_TRAIN_BATCH_SEQS": "32",
    "TTT_GRAD_CLIP": "1.0",
    "VAL_TOKEN_LIMIT": "0",
    "CHECKPOINT_EVERY": "0",
}


FRONTIER_PRESETS: dict[str, Preset] = {
    "control_verified_sota": Preset(
        name="control_verified_sota",
        description="Verified March 23 control: LeakyReLU^2 + legal score-first TTT + Parallel Muon.",
        family="frontier",
        target="cuda",
        launch_mode="torchrun",
        entrypoint="train_gpt_frontier_control.py",
        env=dict(FRONTIER_CONTROL_BASE_ENV),
        min_train_shards=1,
        nproc_per_node=1,
        notes=(
            "Canonical control branch for all frontier comparisons.",
            "Matches the verified LeakyReLU^2 + legal TTT + Parallel Muon stack before cache experiments.",
        ),
        counted_code_paths=("train_gpt_frontier_control.py", "frontier_cache.py", "frontier_checkpoint.py", "flash_attn_interface.py"),
        required_modules=("flash_attn_interface",),
        legality_summary=(
            "Score-first TTT: each chunk is scored under inference mode before any adaptation step.",
            "No cache is active in the control preset.",
            "Artifact bytes are measured as counted code bundle plus compressed model bytes.",
        ),
    ),
    "sota_plus_ngram7": Preset(
        name="sota_plus_ngram7",
        description="Verified control stack plus deterministic 7-gram backward-looking cache.",
        family="frontier",
        target="cuda",
        launch_mode="torchrun",
        entrypoint="train_gpt_frontier_control.py",
        env={
            **FRONTIER_CONTROL_BASE_ENV,
            "CAUSAL_CACHE_MODE": "ngram7",
            "CAUSAL_CACHE_MAX_ORDER": "7",
            "CAUSAL_CACHE_ALPHA": "0.40",
            "CAUSAL_CACHE_MIXING": "fixed",
        },
        min_train_shards=1,
        nproc_per_node=1,
        diff_base="control_verified_sota",
        notes=(
            "Strictly backward-looking fixed-alpha cache.",
            "Keeps legal score-first TTT enabled so the cache is measured on the verified control stack rather than a different base.",
        ),
        counted_code_paths=("train_gpt_frontier_control.py", "frontier_cache.py", "frontier_checkpoint.py", "flash_attn_interface.py"),
        required_modules=("flash_attn_interface",),
        legality_summary=(
            "Cache updates occur only after a scored segment is finalized.",
            "TTT still happens only after a chunk has been scored.",
            "No entropy-adaptive or target-aware mixing is permitted in this preset.",
        ),
    ),
    "sota_plus_ppm_multiorder": Preset(
        name="sota_plus_ppm_multiorder",
        description="Verified control stack plus deterministic multi-order causal cache / PPM-style backoff.",
        family="frontier",
        target="cuda",
        launch_mode="torchrun",
        entrypoint="train_gpt_frontier_control.py",
        env={
            **FRONTIER_CONTROL_BASE_ENV,
            "CAUSAL_CACHE_MODE": "ppm",
            "CAUSAL_CACHE_MAX_ORDER": "7",
            "CAUSAL_CACHE_ALPHA": "0.30",
            "CAUSAL_CACHE_MIXING": "count",
            "CAUSAL_CACHE_COUNT_SMOOTHING": "4.0",
        },
        min_train_shards=1,
        nproc_per_node=1,
        diff_base="control_verified_sota",
        notes=(
            "Multi-order backoff over orders 2..7 with deterministic count-based mixing.",
            "Implements the narrow legal interpretation first: no entropy-adaptive alpha and no target-aware gates.",
        ),
        counted_code_paths=("train_gpt_frontier_control.py", "frontier_cache.py", "frontier_checkpoint.py", "flash_attn_interface.py"),
        required_modules=("flash_attn_interface",),
        legality_summary=(
            "Backoff order selection depends only on previously committed counts.",
            "Mixing is fixed/count-based only and is computed before target scoring is finalized.",
            "Cache and TTT obey separate score-then-adapt phases.",
        ),
    ),
    "sota_plus_ppm_entropy_fixed": Preset(
        name="sota_plus_ppm_entropy_fixed",
        description="PPM backoff with fixed entropy-gated eval-time cache mixing.",
        family="frontier",
        target="cuda",
        launch_mode="torchrun",
        entrypoint="train_gpt_frontier_control.py",
        env={
            **FRONTIER_CONTROL_BASE_ENV,
            "CAUSAL_CACHE_MODE": "ppm",
            "CAUSAL_CACHE_MAX_ORDER": "7",
            "CAUSAL_CACHE_ALPHA": "0.30",
            "CAUSAL_CACHE_MIXING": "entropy",
            "CAUSAL_CACHE_ALPHA_MIN": "0.10",
            "CAUSAL_CACHE_ALPHA_MAX": "0.50",
            "CAUSAL_CACHE_ENTROPY_CENTER": "3.5",
            "CAUSAL_CACHE_ENTROPY_SLOPE": "2.0",
            "CAUSAL_CACHE_COUNT_SMOOTHING": "4.0",
        },
        min_train_shards=1,
        nproc_per_node=1,
        diff_base="sota_plus_ppm_multiorder",
        notes=(
            "Keeps the same legal PPM backoff path, but swaps count-based mixing for fixed entropy gating at eval time.",
            "The 0.10-0.50 alpha range is centered on the current fixed alpha 0.30 starter.",
        ),
        counted_code_paths=("train_gpt_frontier_control.py", "frontier_cache.py", "frontier_checkpoint.py", "flash_attn_interface.py"),
        required_modules=("flash_attn_interface",),
        legality_summary=(
            "Entropy gating uses only the model predictive distribution from the current score step.",
            "No target-aware or future-token signal affects cache weighting.",
            "Cache updates and TTT remain strictly score-first.",
        ),
    ),
    "sota_plus_ppm_entropy_order_adaptive": Preset(
        name="sota_plus_ppm_entropy_order_adaptive",
        description="PPM backoff with order-adaptive entropy-gated eval-time cache mixing.",
        family="frontier",
        target="cuda",
        launch_mode="torchrun",
        entrypoint="train_gpt_frontier_control.py",
        env={
            **FRONTIER_CONTROL_BASE_ENV,
            "CAUSAL_CACHE_MODE": "ppm",
            "CAUSAL_CACHE_MAX_ORDER": "7",
            "CAUSAL_CACHE_ALPHA": "0.30",
            "CAUSAL_CACHE_MIXING": "order_entropy",
            "CAUSAL_CACHE_ALPHA_MIN": "0.10",
            "CAUSAL_CACHE_ALPHA_MAX": "0.50",
            "CAUSAL_CACHE_ENTROPY_SLOPE": "2.0",
            "CAUSAL_CACHE_ORDER_ENTROPY_CENTERS": "7:3.0,6:3.2,5:3.5,4:3.8,3:4.2,2:4.5",
            "CAUSAL_CACHE_COUNT_SMOOTHING": "4.0",
        },
        min_train_shards=1,
        nproc_per_node=1,
        diff_base="sota_plus_ppm_multiorder",
        notes=(
            "Order-adaptive entropy gating on top of the current strongest legal PPM preset.",
            "Matched order selects the entropy center; alpha then interpolates between alpha_min and alpha_max.",
        ),
        counted_code_paths=("train_gpt_frontier_control.py", "frontier_cache.py", "frontier_checkpoint.py", "flash_attn_interface.py"),
        required_modules=("flash_attn_interface",),
        legality_summary=(
            "Order-adaptive gating uses only already-scored model entropy and previously committed cache counts.",
            "No future-token leakage or oracle selection is introduced by the gating rule.",
            "Cache updates and TTT remain strictly score-first.",
        ),
    ),
    "sota_plus_ppm_dirichlet": Preset(
        name="sota_plus_ppm_dirichlet",
        description="PPM backoff with single-pass Dirichlet posterior predictive cache mixing.",
        family="frontier",
        target="cuda",
        launch_mode="torchrun",
        entrypoint="train_gpt_frontier_control.py",
        env={
            **FRONTIER_CONTROL_BASE_ENV,
            "CAUSAL_CACHE_MODE": "ppm",
            "CAUSAL_CACHE_MAX_ORDER": "7",
            "CAUSAL_CACHE_ALPHA": "0.30",
            "CAUSAL_CACHE_MIXING": "dirichlet",
            "CAUSAL_CACHE_COUNT_SMOOTHING": "4.0",
        },
        min_train_shards=1,
        nproc_per_node=1,
        diff_base="sota_plus_ppm_entropy_fixed",
        notes=(
            "Single-pass posterior predictive backoff over orders 2..7 with the model probability as the base prior.",
            "Replaces heuristic alpha mixing with a causal Dirichlet update that only uses already-committed counts.",
        ),
        counted_code_paths=("train_gpt_frontier_control.py", "frontier_cache.py", "frontier_checkpoint.py", "flash_attn_interface.py"),
        required_modules=("flash_attn_interface",),
        legality_summary=(
            "Posterior predictive backoff uses only previously committed counts plus the current score-step model probability.",
            "No future-token signal or target-aware chooser is introduced by the recursive update.",
            "Cache updates and TTT remain strictly score-first.",
        ),
    ),
    "xsaall_fullgptq_prune_plus_cache": Preset(
        name="xsaall_fullgptq_prune_plus_cache",
        description="High-upside legal branch: XSA-all + full GPTQ + selective pruning + causal cache.",
        family="frontier",
        target="cuda",
        launch_mode="torchrun",
        entrypoint="train_gpt_frontier_gptq.py",
        env={
            **FRONTIER_GPTQ_BASE_ENV,
            "CAUSAL_CACHE_MODE": "ngram7",
            "CAUSAL_CACHE_MAX_ORDER": "7",
            "CAUSAL_CACHE_ALPHA": "0.40",
            "CAUSAL_CACHE_MIXING": "fixed",
        },
        min_train_shards=1,
        nproc_per_node=1,
        notes=(
            "Yellow-risk branch: strongest upside, but export/eval complexity is materially higher than the green control family.",
            "Uses full GPTQ inside the training/artifact-construction phase and keeps training-data access out of eval.",
        ),
        counted_code_paths=("train_gpt_frontier_gptq.py", "frontier_cache.py", "frontier_checkpoint.py", "flash_attn_interface.py"),
        required_modules=("flash_attn_interface",),
        legality_summary=(
            "Full GPTQ calibration stays inside the training/artifact-construction phase for this workflow.",
            "Selective pruning only edits exported quantized weights; no validation token affects its own cache score.",
            "Cache remains strictly backward-looking.",
        ),
    ),
    "rotaryfix_bigram3072_legalttt": Preset(
        name="rotaryfix_bigram3072_legalttt",
        description="Green hedge branch: RotaryFix + BIGRAM3072 + legal score-first TTT.",
        family="frontier",
        target="cuda",
        launch_mode="torchrun",
        entrypoint="train_gpt_frontier_control.py",
        env={
            **FRONTIER_CONTROL_BASE_ENV,
            "BIGRAM_VOCAB_SIZE": "3072",
            "ROTARY_FIX": "1",
            "LATE_QAT_THRESHOLD": "0.57",
        },
        min_train_shards=1,
        nproc_per_node=1,
        diff_base="control_verified_sota",
        notes=(
            "Green non-cache hedge if cache branches are too slow or review-risky.",
            "Propagates the training sequence length into Rotary construction on both train and eval paths.",
        ),
        counted_code_paths=("train_gpt_frontier_control.py", "frontier_cache.py", "frontier_checkpoint.py", "flash_attn_interface.py"),
        required_modules=("flash_attn_interface",),
        legality_summary=(
            "Uses the same legal score-first TTT protocol as the verified control.",
            "RotaryFix changes positional encoding propagation only; it does not access future tokens.",
            "No eval-time cache is enabled in this preset.",
        ),
    ),
}


FRONTIER_SCALES: dict[str, RunScale] = {
    "smoke": RunScale(
        name="smoke",
        description="Fast health check with short training and a tiny validation prefix.",
        env={
            "ITERATIONS": "64",
            "MAX_WALLCLOCK_SECONDS": "0",
            "VAL_LOSS_EVERY": "0",
            "VAL_TOKEN_LIMIT": "262144",
            "GPTQ_CALIB_BATCHES": "8",
            "CHECKPOINT_EVERY": "32",
        },
        notes=(
            "Use on local GPUs or a laptop proxy only to verify launch, export, cache legality, and byte reports.",
        ),
    ),
    "half_run": RunScale(
        name="half_run",
        description="Cheaper screening run that preserves the full export path on a reduced wallclock budget.",
        env={
            "ITERATIONS": "20000",
            "MAX_WALLCLOCK_SECONDS": "300",
            "VAL_LOSS_EVERY": "2000",
            "VAL_TOKEN_LIMIT": "1048576",
            "GPTQ_CALIB_BATCHES": "32",
            "CHECKPOINT_EVERY": "250",
        },
        notes=(
            "Primary screening scale for 1xH100 or cheaper cloud boxes.",
            "Still runs export and final eval paths, but on a reduced validation prefix.",
        ),
    ),
    "full_run": RunScale(
        name="full_run",
        description="Canonical 8xH100-style rung matching the intended final timing/eval path.",
        env={
            "ITERATIONS": "20000",
            "MAX_WALLCLOCK_SECONDS": "600",
            "VAL_LOSS_EVERY": "4000",
            "VAL_TOKEN_LIMIT": "0",
            "GPTQ_CALIB_BATCHES": "256",
            "CHECKPOINT_EVERY": "500",
        },
        notes=(
            "Use only for finalists that have already earned promotion from half_run.",
        ),
    ),
}
