#!/usr/bin/env bash
set -euo pipefail
source "$(dirname "$0")/runpod_common.sh"

SFW_TRAIN_TOKENS="${SFW_TRAIN_TOKENS:-16384}" \
SFW_VAL_TOKENS="${SFW_VAL_TOKENS:-4096}" \
SFW_TRAIN_STEPS="${SFW_TRAIN_STEPS:-4}" \
SFW_CALIBRATION_STEPS="${SFW_CALIBRATION_STEPS:-4}" \
SFW_EVAL_BATCHES="${SFW_EVAL_BATCHES:-8}" \
SFW_BATCH_SIZE="${SFW_BATCH_SIZE:-2}" \
SFW_SEQ_LEN="${SFW_SEQ_LEN:-64}" \
SFW_STRIDE="${SFW_STRIDE:-32}" \
SFW_MODEL_DIM="${SFW_MODEL_DIM:-128}" \
SFW_NUM_LAYERS="${SFW_NUM_LAYERS:-4}" \
SFW_NUM_HEADS="${SFW_NUM_HEADS:-4}" \
SFW_NUM_KV_HEADS="${SFW_NUM_KV_HEADS:-2}" \
SFW_MLP_MULT="${SFW_MLP_MULT:-2}" \
SFW_RESIDUAL_RANK="${SFW_RESIDUAL_RANK:-8}" \
SFW_RESIDUAL_TABLE_SIZE="${SFW_RESIDUAL_TABLE_SIZE:-1024}" \
sfw_run_profile smoke "${SFW_SEED:-1337}" "$@"
