#!/usr/bin/env bash
set -euo pipefail

# Run from the repository root, next to train_gpt_mlx.py.
: "${PYTHON:=python3}"

RUN_ID=${RUN_ID:-mlx_novel_trishift_final}

RUN_ID="$RUN_ID" \
ITERATIONS=${ITERATIONS:-20} \
WARMUP_STEPS=${WARMUP_STEPS:-20} \
WARMDOWN_ITERS=${WARMDOWN_ITERS:-3000} \
MAX_WALLCLOCK_SECONDS=${MAX_WALLCLOCK_SECONDS:-600} \
TRAIN_BATCH_TOKENS=${TRAIN_BATCH_TOKENS:-8192} \
GRAD_ACCUM_STEPS=${GRAD_ACCUM_STEPS:-8} \
VAL_LOSS_EVERY=${VAL_LOSS_EVERY:-0} \
VAL_BATCH_SIZE=${VAL_BATCH_SIZE:-8192} \
VAL_MAX_WINDOWS=${VAL_MAX_WINDOWS:-256} \
EVAL_SLIDING_WINDOW=${EVAL_SLIDING_WINDOW:-1} \
EVAL_STRIDE=${EVAL_STRIDE:-960} \
SKIP_FINAL_ROUNDTRIP_EVAL=${SKIP_FINAL_ROUNDTRIP_EVAL:-1} \
MLX_MAX_MICROBATCH_TOKENS=${MLX_MAX_MICROBATCH_TOKENS:-8192} \
NUM_LAYERS=${NUM_LAYERS:-10} \
MODEL_DIM=${MODEL_DIM:-512} \
MLP_MULT=${MLP_MULT:-2.75} \
MLP_HIDDEN_DIM=${MLP_HIDDEN_DIM:-1408} \
MATRIX_LR=${MATRIX_LR:-0.020} \
SCALAR_LR=${SCALAR_LR:-0.020} \
TIED_EMBED_LR=${TIED_EMBED_LR:-0.030} \
MUON_MOMENTUM=${MUON_MOMENTUM:-0.99} \
MUON_MOMENTUM_WARMUP_START=${MUON_MOMENTUM_WARMUP_START:-0.92} \
MUON_MOMENTUM_WARMUP_STEPS=${MUON_MOMENTUM_WARMUP_STEPS:-1500} \
GRAD_CLIP_NORM=${GRAD_CLIP_NORM:-0.30} \
QK_GAIN_INIT=${QK_GAIN_INIT:-1.35} \
ROPE_BASE=${ROPE_BASE:-20000} \
LOGIT_SOFTCAP=${LOGIT_SOFTCAP:-24.0} \
INPUT_MIX_ENABLED=${INPUT_MIX_ENABLED:-1} \
INPUT_MIX_CURR_INIT=${INPUT_MIX_CURR_INIT:-2.20} \
INPUT_MIX_PREV1_INIT=${INPUT_MIX_PREV1_INIT:-0.15} \
INPUT_MIX_PREV2_INIT=${INPUT_MIX_PREV2_INIT:--1.10} \
HARMONIC_EMBED_INIT=${HARMONIC_EMBED_INIT:-0} \
HARMONIC_EMBED_ALPHA=${HARMONIC_EMBED_ALPHA:-0.18} \
HARMONIC_EMBED_POWER=${HARMONIC_EMBED_POWER:-0.50} \
PHASE_RESID_MIX_INIT=${PHASE_RESID_MIX_INIT:-0} \
PHASE_RESID_ANCHOR_MAX=${PHASE_RESID_ANCHOR_MAX:-0.12} \
PHASE_RESID_ANCHOR_MIDPOINT=${PHASE_RESID_ANCHOR_MIDPOINT:-0.58} \
PHASE_RESID_ANCHOR_SHARPNESS=${PHASE_RESID_ANCHOR_SHARPNESS:-10.0} \
MUON_WEIGHT_DECAY=${MUON_WEIGHT_DECAY:-0.018} \
EMBED_WEIGHT_DECAY=${EMBED_WEIGHT_DECAY:-0.012} \
SCALAR_WEIGHT_DECAY=${SCALAR_WEIGHT_DECAY:-0.0} \
FORCE_FP16_EMBED=${FORCE_FP16_EMBED:-0} \
FORCE_FP16_LAST_K_PROJ=${FORCE_FP16_LAST_K_PROJ:-0} \
NOVELSTACK_NAME=${NOVELSTACK_NAME:-TriShift-DecoupledWD} \
"$PYTHON" code/train_gpt_mlx_novelstack.py
