#!/usr/bin/env bash
set -euo pipefail
source "$(dirname "$0")/runpod_common.sh"

SFW_MEMORY_MIN_READ_COUNT="${SFW_MEMORY_MIN_READ_COUNT:-2}" \
SFW_MAINTENANCE_PASSES="${SFW_MAINTENANCE_PASSES:-2}" \
SFW_MAINTENANCE_MODE="${SFW_MAINTENANCE_MODE:-replay}" \
SFW_MAINTENANCE_STEP_SIZE="${SFW_MAINTENANCE_STEP_SIZE:-0.05}" \
SFW_MAINTENANCE_MAX_SLOTS="${SFW_MAINTENANCE_MAX_SLOTS:-128}" \
SFW_MAINTENANCE_METRIC="${SFW_MAINTENANCE_METRIC:-hits}" \
SFW_MAINTENANCE_GRAD_MIX="${SFW_MAINTENANCE_GRAD_MIX:-0.25}" \
SFW_MAINTENANCE_LOSS_EMA_DECAY="${SFW_MAINTENANCE_LOSS_EMA_DECAY:-0.95}" \
SFW_MAINTENANCE_REPLAY_DEPTH="${SFW_MAINTENANCE_REPLAY_DEPTH:-2}" \
SFW_MAINTENANCE_REPLAY_CANDIDATES="${SFW_MAINTENANCE_REPLAY_CANDIDATES:-64}" \
SFW_MAINTENANCE_USE_GRAD="${SFW_MAINTENANCE_USE_GRAD:-0}" \
sfw_run_profile gate2_replay_hits_maint2_slots128_nograd "${SFW_SEED:-1337}" "$@"
