#!/usr/bin/env bash
set -euo pipefail
NCCL_IB_DISABLE="${NCCL_IB_DISABLE:-1}" \
MODEL_VARIANT=challenger \
MUON_WEIGHT_DECAY="${MUON_WEIGHT_DECAY:-0.038}" \
USE_BIGRAM_HASH="${USE_BIGRAM_HASH:-0}" \
USE_SMEARGATE="${USE_SMEARGATE:-0}" \
SWA_ENABLED="${SWA_ENABLED:-0}" \
MAX_WALLCLOCK_SECONDS="${MAX_WALLCLOCK_SECONDS:-600}" \
VAL_LOSS_EVERY="${VAL_LOSS_EVERY:-0}" \
TRAIN_LOG_EVERY="${TRAIN_LOG_EVERY:-200}" \
torchrun --standalone --nproc_per_node="${NPROC_PER_NODE:-8}" train_gpt.py | tee train.log
