#!/usr/bin/env bash
set -euo pipefail

env \
  RUN_ID="${RUN_ID:-mock_8xh100_math}" \
  DRY_RUN_INIT_ONLY=1 \
  SIMULATED_WORLD_SIZE="${SIMULATED_WORLD_SIZE:-8}" \
  DEBUG_DATA_SHARDING_STEPS="${DEBUG_DATA_SHARDING_STEPS:-1}" \
  NUM_LAYERS="${NUM_LAYERS:-24}" \
  BTT_RANK="${BTT_RANK:-1024}" \
  TRAIN_BATCH_TOKENS="${TRAIN_BATCH_TOKENS:-131072}" \
  TRAIN_MICROBATCH_TOKENS="${TRAIN_MICROBATCH_TOKENS:-8192}" \
  LR_SCALE_METHOD="${LR_SCALE_METHOD:-sqrt}" \
  LR_REFERENCE_BATCH_TOKENS="${LR_REFERENCE_BATCH_TOKENS:-16384}" \
  WARMUP_SCALE_METHOD="${WARMUP_SCALE_METHOD:-linear}" \
  WARMUP_REFERENCE_BATCH_TOKENS="${WARMUP_REFERENCE_BATCH_TOKENS:-16384}" \
  WARMUP_STEPS="${WARMUP_STEPS:-1}" \
  VAL_TOKEN_LIMIT="${VAL_TOKEN_LIMIT:-2048}" \
  VAL_BATCH_SIZE="${VAL_BATCH_SIZE:-2048}" \
  python3 train_gpt.py
