_wandb:
    value:
        cli_version: 0.25.1
        e:
            g4rj9sg7cepqs6jxzrfgkojfbv7f2gir:
                args:
                    - --feedback-mode
                    - diagonal
                    - --feedback-rank
                    - "2"
                    - --residual-scale-init
                    - "0.5"
                    - --jacobian-proxy-weight
                    - "0.01"
                codePath: records/track_10min_16mb/2026-03-26_RecurrentSOTA_Feedback/train_gpt_recurrent.py
                codePathLocal: train_gpt_recurrent.py
                cpu_count: 8
                cpu_count_logical: 16
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "1330227675136"
                        used: "39167303680"
                email: nesta.midavaine@prosus.com
                executable: /home/nesta/parameter-golf/.venv/bin/python3
                git:
                    commit: b38248cf6d4a1387d06b2906628c717e59747b11
                    remote: https://github.com/nestamidavaine/parameter-golf.git
                gpu: NVIDIA H200
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Hopper
                      cudaCores: 16896
                      memoryTotal: "150754820096"
                      name: NVIDIA H200
                      uuid: GPU-e312faf2-f704-c38a-00a2-ba4137b99846
                host: computeinstance-e00c09e8zde17qbk32
                memory:
                    total: "211069919232"
                os: Linux-6.11.0-1016-nvidia-x86_64-with-glibc2.39
                program: /home/nesta/parameter-golf/records/track_10min_16mb/2026-03-26_RecurrentSOTA_Feedback/train_gpt_recurrent.py
                python: CPython 3.12.3
                root: /home/nesta/parameter-golf/records/track_10min_16mb/2026-03-26_RecurrentSOTA_Feedback
                startedAt: "2026-03-26T11:00:50.777009Z"
                writerId: g4rj9sg7cepqs6jxzrfgkojfbv7f2gir
        m: []
        python_version: 3.12.3
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 2
                - 13
                - 16
                - 61
            "4": 3.12.3
            "5": 0.25.1
            "10":
                - 20
            "12": 0.25.1
            "13": linux-x86_64
core_end:
    value: 8
core_start:
    value: 3
feedback_mode:
    value: diagonal
feedback_rank:
    value: 2
iterations:
    value: 50
jacobian_proxy_weight:
    value: 0.01
matrix_lr:
    value: 0.025
model_dim:
    value: 512
n_params:
    value: 26927198
num_layers:
    value: 11
num_passes:
    value: 2
residual_scale_init:
    value: 0.5
scalar_lr:
    value: 0.025
seed:
    value: 1337
train_batch_tokens:
    value: 786432
train_seq_len:
    value: 2048
