set -euo pipefail

export RUN_ID="${RUN_ID:-xsa11_bigram3072_2xh100}"
export SEED="${SEED:-1337}"

export BIGRAM_VOCAB_SIZE="${BIGRAM_VOCAB_SIZE:-3072}"
export BIGRAM_DIM="${BIGRAM_DIM:-112}"
export XSA_LAST_N="${XSA_LAST_N:-11}"
export TARGET_MB="${TARGET_MB:-15.90}"

export TTT_ENABLED="${TTT_ENABLED:-1}"
export TTT_OPTIMIZER="${TTT_OPTIMIZER:-sgd}"
export TTT_LR="${TTT_LR:-0.002}"
export TTT_MOMENTUM="${TTT_MOMENTUM:-0.9}"
export TTT_WEIGHT_DECAY="${TTT_WEIGHT_DECAY:-0.0}"
export TTT_EPOCHS="${TTT_EPOCHS:-3}"
export TTT_FREEZE_BLOCKS="${TTT_FREEZE_BLOCKS:-0}"
export TTT_BATCH_SEQS="${TTT_BATCH_SEQS:-32}"
export TTT_CHUNK_TOKENS="${TTT_CHUNK_TOKENS:-32768}"
export TTT_GRAD_CLIP="${TTT_GRAD_CLIP:-1.0}"

export ITERATIONS="${ITERATIONS:-9000}"
export MAX_WALLCLOCK_SECONDS="${MAX_WALLCLOCK_SECONDS:-2400}"
export TRAIN_BATCH_TOKENS="${TRAIN_BATCH_TOKENS:-786432}"
export VAL_LOSS_EVERY="${VAL_LOSS_EVERY:-999999}"
export EVAL_STRIDE="${EVAL_STRIDE:-64}"
export FLASH_ATTN3_MODE="${FLASH_ATTN3_MODE:-auto}"

torchrun --standalone --nproc_per_node=2 train_gpt.py
