#!/usr/bin/env bash
# Launcher for the 8xH100 leaderboard run.
#
#   bash run_leaderboard_8xh100.sh
#
# The script assumes the fineweb_sp1024 dataset + tokenizer have already been
# downloaded into ./data/.  See the repository README for the download commands.
set -euo pipefail

: "${DATA_PATH:=./data/datasets/fineweb10B_sp1024}"
: "${TOKENIZER_PATH:=./data/tokenizers/fineweb_1024_bpe.model}"
: "${SEED:=42}"
: "${RUN_ID:=linattn_hybrid_$(date +%s)}"

export NCCL_IB_DISABLE=1
export TORCH_CUDNN_V8_API_ENABLED=1
export CUDA_DEVICE_MAX_CONNECTIONS=1

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TRAIN="${HERE}/train_gpt.py"

DATA_PATH="${DATA_PATH}" \
TOKENIZER_PATH="${TOKENIZER_PATH}" \
SEED="${SEED}" \
RUN_ID="${RUN_ID}" \
MAX_WALLCLOCK_SECONDS="${MAX_WALLCLOCK_SECONDS:-595}" \
ITERATIONS="${ITERATIONS:-2400}" \
WARMUP_STEPS="${WARMUP_STEPS:-60}" \
WARMDOWN_START="${WARMDOWN_START:-1900}" \
WARMDOWN_END="${WARMDOWN_END:-2400}" \
VAL_LOSS_EVERY="${VAL_LOSS_EVERY:-400}" \
TRAIN_LOG_EVERY="${TRAIN_LOG_EVERY:-50}" \
TRAIN_SEQ_LEN="${TRAIN_SEQ_LEN:-1024}" \
TRAIN_BATCH_TOKENS="${TRAIN_BATCH_TOKENS:-524288}" \
VOCAB_SIZE="${VOCAB_SIZE:-1024}" \
NUM_LAYERS="${NUM_LAYERS:-12}" \
MODEL_DIM="${MODEL_DIM:-512}" \
NUM_HEADS="${NUM_HEADS:-8}" \
NUM_KV_HEADS="${NUM_KV_HEADS:-2}" \
MLP_MULT_NUM="${MLP_MULT_NUM:-5}" \
MLP_MULT_DEN="${MLP_MULT_DEN:-2}" \
ROPE_FRAC="${ROPE_FRAC:-0.5}" \
SWA_WINDOW="${SWA_WINDOW:-512}" \
SWA_LAYERS="${SWA_LAYERS:-8}" \
MIXER_LAYERS="${MIXER_LAYERS:-1,3,5,7,9}" \
MIXER_CHUNK="${MIXER_CHUNK:-64}" \
MIXER_STATE_DIM="${MIXER_STATE_DIM:-64}" \
MIXER_HEADS="${MIXER_HEADS:-4}" \
MATRIX_LR="${MATRIX_LR:-0.028}" \
TIED_EMBED_LR="${TIED_EMBED_LR:-0.03}" \
SCALAR_LR="${SCALAR_LR:-0.032}" \
HEAD_LR="${HEAD_LR:-0.008}" \
MUON_MOMENTUM="${MUON_MOMENTUM:-0.95}" \
MUON_WD="${MUON_WD:-0.05}" \
GRAD_CLIP="${GRAD_CLIP:-1.0}" \
QK_GAIN_INIT="${QK_GAIN_INIT:-4.0}" \
EMA_DECAY="${EMA_DECAY:-0.9965}" \
EMA_INTERVAL="${EMA_INTERVAL:-32}" \
SWA_START="${SWA_START:-2100}" \
SWA_INTERVAL="${SWA_INTERVAL:-75}" \
QAT_START="${QAT_START:-1950}" \
QAT_BITS_MATRIX="${QAT_BITS_MATRIX:-6}" \
GPTQ_MATRIX_BITS="${GPTQ_MATRIX_BITS:-6}" \
GPTQ_EMBED_BITS="${GPTQ_EMBED_BITS:-7}" \
GPTQ_SIGMA_ATTN="${GPTQ_SIGMA_ATTN:-3.1}" \
GPTQ_SIGMA_MLP="${GPTQ_SIGMA_MLP:-3.0}" \
GPTQ_SIGMA_MIXER="${GPTQ_SIGMA_MIXER:-3.2}" \
GPTQ_SIGMA_EMBED="${GPTQ_SIGMA_EMBED:-3.4}" \
ARTIFACT_CAP_BYTES="${ARTIFACT_CAP_BYTES:-16000000}" \
EVAL_STRIDE="${EVAL_STRIDE:-64}" \
EVAL_CTX="${EVAL_CTX:-1024}" \
torchrun --standalone --nproc_per_node=8 "${TRAIN}"
