#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../.." && pwd)"
RECORD_DIR="${ROOT}/records/track_non_record_16mb/2026-04-03_DeepFloor"
PYTHON_BIN="${PYTHON_BIN:-${ROOT}/.venv/bin/python}"
ENWIK8_PATH="${ENWIK8_PATH:-/workspace/data/enwik8}"
OUTPUT_JSON="${OUTPUT_JSON:-${RECORD_DIR}/candidate_result_seed1337.json}"
TRAIN_LOG="${TRAIN_LOG:-${RECORD_DIR}/train_seed1337.log}"
SUBMISSION_JSON="${SUBMISSION_JSON:-${RECORD_DIR}/submission.json}"
DEVICE="${DEVICE:-cuda}"

if [[ ! -f "${ENWIK8_PATH}" ]]; then
  echo "[error] ENWIK8_PATH not found: ${ENWIK8_PATH}" >&2
  exit 1
fi

"${PYTHON_BIN}" "${RECORD_DIR}/freeze_submission_snapshot.py"

mkdir -p "$(dirname "${OUTPUT_JSON}")" "$(dirname "${TRAIN_LOG}")"

env \
  ENWIK8_PATH="${ENWIK8_PATH}" \
  OUTPUT_JSON="${OUTPUT_JSON}" \
  DEVICE="${DEVICE}" \
  SEED="${SEED:-1337}" \
  TRAIN_STEPS="${TRAIN_STEPS:-1}" \
  EVAL_BATCHES="${EVAL_BATCHES:-1}" \
  SEQ_LEN="${SEQ_LEN:-16}" \
  STRIDE="${STRIDE:-8}" \
  BATCH_SIZE="${BATCH_SIZE:-2}" \
  RECURRENT_DIM="${RECURRENT_DIM:-32}" \
  RECURRENT_HEADS="${RECURRENT_HEADS:-4}" \
  NUM_DISTINCT_BLOCKS="${NUM_DISTINCT_BLOCKS:-1}" \
  VIEW_COUNT="${VIEW_COUNT:-2}" \
  VIEW_COMBINATION="${VIEW_COMBINATION:-average}" \
  CROSS_TOKEN_MODE="${CROSS_TOKEN_MODE:-fused}" \
  BLOCK_HAS_RESIDUAL="${BLOCK_HAS_RESIDUAL:-1}" \
  BLOCK_NONLINEARITY="${BLOCK_NONLINEARITY:-gelu}" \
  RECURRENCE_STEP_SIZE="${RECURRENCE_STEP_SIZE:-1.0}" \
  STATE_DECAY="${STATE_DECAY:-1.0}" \
  CONTRACTION_TARGET="${CONTRACTION_TARGET:-0.995}" \
  TRAIN_RECURRENCE_STEPS="${TRAIN_RECURRENCE_STEPS:-6}" \
  EVAL_RECURRENCE_STEPS="${EVAL_RECURRENCE_STEPS:-8}" \
  TBPTT_CHUNK="${TBPTT_CHUNK:-16}" \
  NORM_INTERVAL_K="${NORM_INTERVAL_K:-16}" \
  TRAIN_FLOOR_INTERVAL="${TRAIN_FLOOR_INTERVAL:-8}" \
  FLOOR_MIN_INTERVAL="${FLOOR_MIN_INTERVAL:-1}" \
  FLOOR_MAX_INTERVAL="${FLOOR_MAX_INTERVAL:-3}" \
  FLOOR_THRESHOLD="${FLOOR_THRESHOLD:-0.01}" \
  KERNEL_FEATURE_MAP="${KERNEL_FEATURE_MAP:-identity}" \
  ACCUMULATOR_DECAY="${ACCUMULATOR_DECAY:-0.999}" \
  STATE_CORE="${STATE_CORE:-scalar_decay}" \
  HIPPO_DELTA_SCALE="${HIPPO_DELTA_SCALE:-0.0}" \
  HIPPO_RANK="${HIPPO_RANK:-1}" \
  QUANTIZATION="${QUANTIZATION:-ternary}" \
  JACOBIAN_LAMBDA="${JACOBIAN_LAMBDA:-0.01}" \
  STOCHASTIC_ROUND_P="${STOCHASTIC_ROUND_P:-0.0}" \
  BASE_LR="${BASE_LR:-0.002}" \
  WEIGHT_DECAY="${WEIGHT_DECAY:-0.01}" \
  GRAD_CLIP_NORM="${GRAD_CLIP_NORM:-1.0}" \
  WARMUP_STEPS="${WARMUP_STEPS:-4}" \
  MIN_LR_SCALE="${MIN_LR_SCALE:-0.1}" \
  CACHE_DATASET_ON_DEVICE="${CACHE_DATASET_ON_DEVICE:-0}" \
  "${PYTHON_BIN}" "${RECORD_DIR}/train_gpt.py" | tee "${TRAIN_LOG}"

"${PYTHON_BIN}" "${RECORD_DIR}/build_submission_json.py" \
  --result-json "${OUTPUT_JSON}" \
  --output-json "${SUBMISSION_JSON}"
