#!/bin/bash
set -euo pipefail

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_DIR"

export PYTHONPATH="$REPO_DIR/flash-attention/hopper:${PYTHONPATH:-}"
NPROC="${NPROC:-8}"
SEED="${SEED:-1337}"
RUN_ID="${RUN_ID:-edge_int5_b64_pd001_$(date +%Y%m%d_%H%M%S)}"

echo "RUN_ID=$RUN_ID"
env \
  RUN_ID="$RUN_ID" SEED="$SEED" \
  NUM_LAYERS=11 MODEL_DIM=512 NUM_HEADS=8 NUM_KV_HEADS=8 MLP_MULT=3.5 \
  BIGRAM_VOCAB_SIZE=8192 BIGRAM_DIM=128 XSA_LAST_N=11 ROPE_DIMS=16 \
  TRAIN_SEQ_LEN=2048 EVAL_SEQ_LEN=2048 TRAIN_BATCH_TOKENS=786432 \
  MAX_WALLCLOCK_SECONDS=600 WARMDOWN_ITERS=3500 VAL_LOSS_EVERY=0 EVAL_STRIDE=64 \
  MATRIX_LR=0.025 SCALAR_LR=0.025 TIED_EMBED_LR=0.035 MUON_MOMENTUM=0.99 MUON_WD=0.04 \
  QAT_ENABLED=0 LATE_QAT_THRESHOLD=0.50 \
  QUANT_INT_CATEGORIES=mlp,attn QUANT_MLP_CLIP_RANGE=15 QUANT_ATTN_CLIP_RANGE=15 \
  GPTQ_BLOCK_SIZE=64 GPTQ_PERCDAMP=0.01 GPTQ_CALIBRATION_SAMPLES=256 \
  QUANT_ARTIFACT_NAME=final_model.int5mix.ptz \
  TTT_EVAL_ENABLED=1 TTT_OPTIMIZER=adamw TTT_LR=1e-4 TTT_EPOCHS=3 \
  TTT_CHUNK_TOKENS=131072 TTT_FREEZE_BLOCKS=9 TTT_FREEZE_EMBED=1 \
  TTT_GRAD_CLIP=1.0 TTT_MAX_TRAIN_CHUNKS=200 TTT_EMA_DECAY=0.995 \
  POST_TTT_TEMP_ENABLED=1 POST_TTT_TEMPERATURE=0.98 \
  torchrun --standalone --nproc_per_node="$NPROC" train_gpt_576plus.py

echo "saved: results/autoruns/${RUN_ID}/result_summary.json"
