#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

# Stage 1/2: cheap wide search. No precious-run mindset.
# We cap runs by wallclock and only ask for one intermediate validation.
SAME_SURFACE_MINUTES="${SAME_SURFACE_MINUTES:-60}"
CRAZY_MINUTES="${CRAZY_MINUTES:-60}"
BEST_BETS_MINUTES="${BEST_BETS_MINUTES:-60}"
MIN_SECONDS_LEFT_TO_START="${MIN_SECONDS_LEFT_TO_START:-600}"
NPROC_PER_NODE="${NPROC_PER_NODE:-1}"

echo "=== Stage 1/3: same-surface brute force ==="
TOTAL_BUDGET_MINUTES="$SAME_SURFACE_MINUTES" \
MIN_SECONDS_LEFT_TO_START="$MIN_SECONDS_LEFT_TO_START" \
MAX_WALLCLOCK_SECONDS="${SAME_MAX_WALLCLOCK_SECONDS:-240}" \
VAL_LOSS_EVERY="${SAME_VAL_LOSS_EVERY:-400}" \
TRAIN_LOG_EVERY="${SAME_TRAIN_LOG_EVERY:-100}" \
AUTO_STOP_STEP="${SAME_AUTO_STOP_STEP:-0}" \
AUTO_STOP_MAX_VAL_BPB="${SAME_AUTO_STOP_MAX_VAL_BPB:-0}" \
NPROC_PER_NODE="$NPROC_PER_NODE" \
bash scripts/run_same_surface_120m.sh

echo
echo "=== Stage 2/3: crazy brute force ==="
TOTAL_BUDGET_MINUTES="$CRAZY_MINUTES" \
MIN_SECONDS_LEFT_TO_START="$MIN_SECONDS_LEFT_TO_START" \
MAX_WALLCLOCK_SECONDS="${CRAZY_MAX_WALLCLOCK_SECONDS:-240}" \
VAL_LOSS_EVERY="${CRAZY_VAL_LOSS_EVERY:-400}" \
TRAIN_LOG_EVERY="${CRAZY_TRAIN_LOG_EVERY:-100}" \
AUTO_STOP_STEP="${CRAZY_AUTO_STOP_STEP:-0}" \
AUTO_STOP_MAX_VAL_BPB="${CRAZY_AUTO_STOP_MAX_VAL_BPB:-0}" \
NPROC_PER_NODE="$NPROC_PER_NODE" \
bash scripts/run_crazy_120m.sh

echo
echo "=== Stage 3/3: best-bets confirmation ==="
TOTAL_BUDGET_MINUTES="$BEST_BETS_MINUTES" \
MIN_SECONDS_LEFT_TO_START="$MIN_SECONDS_LEFT_TO_START" \
MAX_WALLCLOCK_SECONDS="${BEST_MAX_WALLCLOCK_SECONDS:-360}" \
VAL_LOSS_EVERY="${BEST_VAL_LOSS_EVERY:-600}" \
TRAIN_LOG_EVERY="${BEST_TRAIN_LOG_EVERY:-100}" \
AUTO_STOP_STEP="${BEST_AUTO_STOP_STEP:-600}" \
AUTO_STOP_MAX_VAL_BPB="${BEST_AUTO_STOP_MAX_VAL_BPB:-1.52}" \
RUN_ID_PREFIX="${RUN_ID_PREFIX:-bestbetfast}" \
NPROC_PER_NODE="$NPROC_PER_NODE" \
bash scripts/run_best_bets_120m.sh
