#!/bin/bash
set -euo pipefail

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_DIR"

export PYTHONPATH="$REPO_DIR/flash-attention/hopper:${PYTHONPATH:-}"
NPROC="${NPROC:-8}"
SEED="${SEED:-1337}"
RUN_ID="${RUN_ID:-streaker_$(date +%Y%m%d_%H%M%S)}"

echo "RUN_ID=$RUN_ID"
env \
  RUN_ID="$RUN_ID" SEED="$SEED" \
  NUM_LAYERS=11 MODEL_DIM=512 NUM_HEADS=8 NUM_KV_HEADS=4 MLP_MULT=3 \
  BIGRAM_VOCAB_SIZE=2048 BIGRAM_DIM=128 XSA_LAST_N=11 ROPE_DIMS=16 \
  TRAIN_SEQ_LEN=2048 EVAL_SEQ_LEN=2048 TRAIN_BATCH_TOKENS=786432 \
  MAX_WALLCLOCK_SECONDS=600 WARMDOWN_ITERS=3500 VAL_LOSS_EVERY=0 EVAL_STRIDE=64 \
  MATRIX_LR=0.025 SCALAR_LR=0.025 TIED_EMBED_LR=0.035 MUON_MOMENTUM=0.99 MUON_WD=0.04 \
  QAT_ENABLED=0 LATE_QAT_THRESHOLD=0.15 LN_SCALE=1 \
  VE_ENABLED=1 VE_DIM=128 VE_LAYERS="9,10" \
  DTG_ENABLED=0 \
  SWA_ENABLED=1 SWA_EVERY=50 \
  GPTQ_BLOCK_SIZE=64 GPTQ_PERCDAMP=0.01 GPTQ_CALIBRATION_SAMPLES=256 \
  TARGET_MB=15.9 \
  torchrun --standalone --nproc_per_node="$NPROC" train_gpt_streaker.py

echo "done: RUN_ID=$RUN_ID"
