#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

SAME_SURFACE_MINUTES="${SAME_SURFACE_MINUTES:-120}"
CRAZY_MINUTES="${CRAZY_MINUTES:-120}"
BEST_BETS_MINUTES="${BEST_BETS_MINUTES:-120}"
MIN_SECONDS_LEFT_TO_START="${MIN_SECONDS_LEFT_TO_START:-900}"
NPROC_PER_NODE="${NPROC_PER_NODE:-1}"

echo "=== Bucket 1/3: same winner-surface, different mechanisms ==="
TOTAL_BUDGET_MINUTES="$SAME_SURFACE_MINUTES" \
MIN_SECONDS_LEFT_TO_START="$MIN_SECONDS_LEFT_TO_START" \
AUTO_STOP_STEP="${SAME_AUTO_STOP_STEP:-1000}" \
AUTO_STOP_MAX_VAL_BPB="${SAME_AUTO_STOP_MAX_VAL_BPB:-1.388}" \
NPROC_PER_NODE="$NPROC_PER_NODE" \
bash scripts/run_same_surface_120m.sh

echo
echo "=== Bucket 2/3: crazy mechanisms ==="
TOTAL_BUDGET_MINUTES="$CRAZY_MINUTES" \
MIN_SECONDS_LEFT_TO_START="$MIN_SECONDS_LEFT_TO_START" \
AUTO_STOP_STEP="${CRAZY_AUTO_STOP_STEP:-1000}" \
AUTO_STOP_MAX_VAL_BPB="${CRAZY_AUTO_STOP_MAX_VAL_BPB:-1.395}" \
NPROC_PER_NODE="$NPROC_PER_NODE" \
bash scripts/run_crazy_120m.sh

echo
echo "=== Bucket 3/3: best current bets ==="
TOTAL_BUDGET_MINUTES="$BEST_BETS_MINUTES" \
MIN_SECONDS_LEFT_TO_START="$MIN_SECONDS_LEFT_TO_START" \
AUTO_STOP_STEP="${BEST_AUTO_STOP_STEP:-1000}" \
AUTO_STOP_MAX_VAL_BPB="${BEST_AUTO_STOP_MAX_VAL_BPB:-1.388}" \
RUN_ID_PREFIX="${RUN_ID_PREFIX:-bestbet}" \
NPROC_PER_NODE="$NPROC_PER_NODE" \
bash scripts/run_best_bets_120m.sh
