#!/usr/bin/env bash
set -euo pipefail

source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/runpod_common.sh"

SFW_ITERATIONS="${SFW_ITERATIONS:-64}" \
SFW_TRAIN_BATCH_TOKENS="${SFW_TRAIN_BATCH_TOKENS:-131072}" \
SFW_VAL_BATCH_SIZE="${SFW_VAL_BATCH_SIZE:-65536}" \
SFW_VAL_TOKEN_LIMIT="${SFW_VAL_TOKEN_LIMIT:-524288}" \
SFW_TRAIN_LOG_EVERY="${SFW_TRAIN_LOG_EVERY:-16}" \
SFW_VAL_LOSS_EVERY="${SFW_VAL_LOSS_EVERY:-64}" \
SFW_MAX_WALLCLOCK_SECONDS="${SFW_MAX_WALLCLOCK_SECONDS:-120}" \
SFW_RESIDUAL_TABLE_SIZE="${SFW_RESIDUAL_TABLE_SIZE:-16384}" \
sfw_run_profile smoke "${SFW_SEED:-1337}"
