#!/usr/bin/env bash
set -euo pipefail

source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/runpod_common.sh"

SFW_ITERATIONS="${SFW_ITERATIONS:-20000}" \
SFW_TRAIN_BATCH_TOKENS="${SFW_TRAIN_BATCH_TOKENS:-786432}" \
SFW_VAL_BATCH_SIZE="${SFW_VAL_BATCH_SIZE:-524288}" \
SFW_VAL_LOSS_EVERY="${SFW_VAL_LOSS_EVERY:-4000}" \
SFW_TRAIN_LOG_EVERY="${SFW_TRAIN_LOG_EVERY:-500}" \
SFW_MAX_WALLCLOCK_SECONDS="${SFW_MAX_WALLCLOCK_SECONDS:-600}" \
SFW_RESIDUAL_TABLE_SIZE="${SFW_RESIDUAL_TABLE_SIZE:-49152}" \
SFW_XSA_LAST_N="${SFW_XSA_LAST_N:-4}" \
sfw_run_profile full "${SFW_SEED:-1337}"
