#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "${SCRIPT_DIR}/../../.." && pwd)"

export RUN_ID="${RUN_ID:-fp16emb_mlp992_slide64_size_repair_probe}"
export DATA_PATH="${DATA_PATH:-${ROOT}/data/datasets/fineweb10B_sp1024}"
export TOKENIZER_PATH="${TOKENIZER_PATH:-${ROOT}/data/tokenizers/fineweb_1024_bpe.model}"
export VOCAB_SIZE="${VOCAB_SIZE:-1024}"
export MAX_WALLCLOCK_SECONDS="${MAX_WALLCLOCK_SECONDS:-0}"
export TRAIN_LOG_EVERY="${TRAIN_LOG_EVERY:-200}"
export VAL_LOSS_EVERY="${VAL_LOSS_EVERY:-0}"
export NCCL_DEBUG="${NCCL_DEBUG:-INFO}"
export TORCH_DISTRIBUTED_DEBUG="${TORCH_DISTRIBUTED_DEBUG:-DETAIL}"
export TORCH_NCCL_DUMP_ON_TIMEOUT="${TORCH_NCCL_DUMP_ON_TIMEOUT:-1}"
export TORCH_NCCL_TRACE_BUFFER_SIZE="${TORCH_NCCL_TRACE_BUFFER_SIZE:-1048576}"
export TORCH_SHOW_CPP_STACKTRACES="${TORCH_SHOW_CPP_STACKTRACES:-1}"
export CUDA_LAUNCH_BLOCKING="${CUDA_LAUNCH_BLOCKING:-1}"
export EVAL_STRIDE="${EVAL_STRIDE:-64}"
export EVAL_BATCH_SEQS="${EVAL_BATCH_SEQS:-128}"
export TTT_BATCH_SIZE="${TTT_BATCH_SIZE:-32}"
export INT8_KEEP_FLOAT_FP16_NAME_PATTERNS="${INT8_KEEP_FLOAT_FP16_NAME_PATTERNS:-tok_emb.weight}"
export MLP_HIDDEN="${MLP_HIDDEN:-992}"
export ITERATIONS="${ITERATIONS:-1600}"
export SKIP_TTT_EVAL="${SKIP_TTT_EVAL:-1}"

exec torchrun --standalone --nproc_per_node=8 "${SCRIPT_DIR}/train_gpt.py"
