#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "${ROOT_DIR}"

STAMP="${STAMP:-$(date +%Y%m%d_%H%M%S)}"
OUT_DIR="${OUT_DIR:-${ROOT_DIR}/logs/skc_matrix_${STAMP}}"
mkdir -p "${OUT_DIR}"
export MATRIX_LOCK_BATCH_TOKENS="${MATRIX_LOCK_BATCH_TOKENS:-49152}"

if ! command -v nvidia-smi >/dev/null 2>&1; then
  echo "ERROR: nvidia-smi not found. Run this script on the training pod." >&2
  exit 2
fi

run_one() {
  local rid="$1"; shift
  local log_file="${OUT_DIR}/${rid}.txt"
  local launch_log="${OUT_DIR}/${rid}.launcher.log"
  echo "=== START ${rid} $(date -Is) ===" | tee -a "${launch_log}"
  env "$@" RUN_ID="$rid" bash "${ROOT_DIR}/run_god_tier_skc.sh" >> "${log_file}" 2>&1
  python3 "${ROOT_DIR}/scratch/summarize_skc_matrix.py" \
    --log-dir "${OUT_DIR}" \
    --run-id "${rid}" \
    --out-csv "${OUT_DIR}/final_comparison_table.csv" \
    --out-json "${OUT_DIR}/final_comparison_table.json" \
    --assert-gate-trained \
    --assert-no-nan \
    --assert-batch-tokens "${MATRIX_LOCK_BATCH_TOKENS}" \
    || { echo "RUN ${rid} failed invariant" | tee -a "${launch_log}"; exit 4; }
  echo "=== END ${rid} $(date -Is) ===" | tee -a "${launch_log}"
}

common=(
  AUTO_TUNE=0
  SKIP_BUILD_SUBMISSION=1
  DIAGNOSTICS_ENABLED=1
  COMPILE_MODE=none
  DDP_FIND_UNUSED_PARAMETERS=1
  TRAIN_LOG_EVERY=1
  TRAIN_LOG_EVERY_FRACTION=0
  VAL_LOSS_EVERY=0
  VAL_LOSS_EVERY_FRACTION=0
  EXPORT_ALIGNED_TRAIN=0
  EXPORT_PROXY_EVAL=0
  TRAINING_DYNAMICS_ONLY=1
  ITERATIONS="${ITERATIONS:-200000}"
  MAX_WALLCLOCK_SECONDS="${MAX_WALLCLOCK_SECONDS:-540}"
  RUN_TIMEOUT_SECONDS="${RUN_TIMEOUT_SECONDS:-2100}"
  TRITON_ENGRAM_ENABLED=0
  SLIDING_EVAL=0
  FINAL_EVAL_SEQUENTIAL_CARRY=0
  RUNTIME_PATH_POLICY=legacy
  ADAM_WD=0.0
  SKC_CAUSAL_PROBE=1
  ENG_CAUSAL_PROBE=1
  BRANCH_AMP_LOG=1
  ENG_GATE_LOG=1
  SKC_PROBE_EVERY="${SKC_PROBE_EVERY:-50}"
  SKC_PROBE_WARMUP="${SKC_PROBE_WARMUP:-50}"
  SKC_RESIDUAL_SCALE_INIT="${SKC_RESIDUAL_SCALE_INIT:-0.15}"
  SKC_AMP_RAMP_FRACTION="${SKC_AMP_RAMP_FRACTION:-0.3}"
  SKC_STRUCT_LR_MULT="${SKC_STRUCT_LR_MULT:-1.5}"
  HEAD_LR_MULT="${HEAD_LR_MULT:-1.0}"
  ENGRAM_TAPER_START="${ENGRAM_TAPER_START:-0.95}"
  ENGRAM_TAPER_END="${ENGRAM_TAPER_END:-0.99}"
  ENG_WRITE_EVERY="${ENG_WRITE_EVERY:-1}"
)

# Phase 0 dry-run (short)
run_one P0_dryrun "${common[@]}" ITERATIONS=3 MAX_WALLCLOCK_SECONDS=90 RUN_TIMEOUT_SECONDS=300 SKC_PROBE_EVERY=1 SKC_PROBE_WARMUP=0 SCALES_LR_MULT=1.0 RECURRENCE_START_FRACTION=0.35 BIGRAM_HASH_ENABLED=1

# Track A
run_one A0 "${common[@]}" SCALES_LR_MULT=1.0 RECURRENCE_START_FRACTION=0.35 BIGRAM_HASH_ENABLED=1
run_one A1 "${common[@]}" SCALES_LR_MULT=1.0 RECURRENCE_START_FRACTION=0.35 BIGRAM_HASH_ENABLED=1 SKC_RESIDUAL_SCALE_INIT=0.15 SKC_AMP_RAMP_FRACTION=0.3
run_one A2 "${common[@]}" SCALES_LR_MULT=1.0 RECURRENCE_START_FRACTION=0.35 BIGRAM_HASH_ENABLED=1 SKC_STRUCT_LR_MULT=1.5
run_one A3 "${common[@]}" SCALES_LR_MULT=1.0 RECURRENCE_START_FRACTION=0.35 BIGRAM_HASH_ENABLED=1 SKC_RESIDUAL_SCALE_INIT=0.15 SKC_AMP_RAMP_FRACTION=0.3 SKC_STRUCT_LR_MULT=1.5
run_one A4 "${common[@]}" SCALES_LR_MULT=1.0 RECURRENCE_START_FRACTION=0.35 BIGRAM_HASH_ENABLED=1 SKC_RESIDUAL_SCALE_INIT=0.15 SKC_AMP_RAMP_FRACTION=0.3 SKC_STRUCT_LR_MULT=1.5 HEAD_LR_MULT=0.7

# Track B
run_one B0 "${common[@]}" SCALES_LR_MULT=1.0 RECURRENCE_START_FRACTION=0.35 BIGRAM_HASH_ENABLED=1
run_one B1 "${common[@]}" SCALES_LR_MULT=1.0 RECURRENCE_START_FRACTION=0.35 BIGRAM_HASH_ENABLED=1 ENGRAM_TAPER_START=0.95 ENGRAM_TAPER_END=0.99
run_one B2 "${common[@]}" SCALES_LR_MULT=1.0 RECURRENCE_START_FRACTION=0.35 BIGRAM_HASH_ENABLED=1 ENGRAM_TAPER_START=0.95 ENGRAM_TAPER_END=0.99 ENG_GATE_LOG=1
run_one B3 "${common[@]}" SCALES_LR_MULT=1.0 RECURRENCE_START_FRACTION=0.35 BIGRAM_HASH_ENABLED=1 ENGRAM_TAPER_START=0.95 ENGRAM_TAPER_END=0.99 ENG_WRITE_EVERY=2
run_one B4 "${common[@]}" SCALES_LR_MULT=1.0 RECURRENCE_START_FRACTION=0.35 BIGRAM_HASH_ENABLED=0

# Track C
run_one C0 "${common[@]}" SCALES_LR_MULT=1.0 RECURRENCE_START_FRACTION=0.35 BIGRAM_HASH_ENABLED=1 SKC_RESIDUAL_SCALE_INIT=0.15 SKC_AMP_RAMP_FRACTION=0.3 SKC_STRUCT_LR_MULT=1.5 ENGRAM_TAPER_START=0.95 ENGRAM_TAPER_END=0.99
run_one C1 "${common[@]}" SCALES_LR_MULT=1.0 RECURRENCE_START_FRACTION=0.35 BIGRAM_HASH_ENABLED=1 SKC_RESIDUAL_SCALE_INIT=0.15 SKC_AMP_RAMP_FRACTION=0.3 SKC_STRUCT_LR_MULT=1.5 ENGRAM_TAPER_START=0.95 ENGRAM_TAPER_END=0.99 ENG_TO_SKC_MODE=gate
run_one C2 "${common[@]}" SCALES_LR_MULT=1.0 RECURRENCE_START_FRACTION=0.35 BIGRAM_HASH_ENABLED=1 SKC_RESIDUAL_SCALE_INIT=0.15 SKC_AMP_RAMP_FRACTION=0.3 SKC_STRUCT_LR_MULT=1.5 ENGRAM_TAPER_START=0.95 ENGRAM_TAPER_END=0.99 ENG_TO_SKC_MODE=bias
run_one C3 "${common[@]}" SCALES_LR_MULT=1.0 RECURRENCE_START_FRACTION=0.35 BIGRAM_HASH_ENABLED=1 SKC_RESIDUAL_SCALE_INIT=0.15 SKC_AMP_RAMP_FRACTION=0.3 SKC_STRUCT_LR_MULT=1.5 ENGRAM_TAPER_START=0.95 ENGRAM_TAPER_END=0.99 ENG_TO_SKC_MODE=gate HEAD_LR_MULT=0.7
run_one C4 "${common[@]}" SCALES_LR_MULT=1.0 RECURRENCE_START_FRACTION=0.35 BIGRAM_HASH_ENABLED=0 SKC_RESIDUAL_SCALE_INIT=0.15 SKC_AMP_RAMP_FRACTION=0.3 SKC_STRUCT_LR_MULT=1.5 ENGRAM_TAPER_START=0.95 ENGRAM_TAPER_END=0.99 ENG_TO_SKC_MODE=gate

python3 "${ROOT_DIR}/scratch/summarize_skc_matrix.py" --log-dir "${OUT_DIR}" --out-csv "${OUT_DIR}/final_comparison_table.csv" --out-json "${OUT_DIR}/final_comparison_table.json"
echo "DONE: ${OUT_DIR}"
