#!/usr/bin/env bash
set -euo pipefail
cd /workspace
nohup env TRITON_ENGRAM_ENABLED=0 AUTO_TUNE=0 DIAGNOSTICS_ENABLED=1 COMPILE_MODE=none DDP_FIND_UNUSED_PARAMETERS=1 TRAIN_LOG_EVERY=1 TRAIN_LOG_EVERY_FRACTION=0 VAL_LOSS_EVERY=50 VAL_LOSS_EVERY_FRACTION=0 EXPORT_ALIGNED_TRAIN=0 EXPORT_PROXY_EVAL=0 RUNTIME_PATH_POLICY=legacy TRAIN_BATCH_TOKENS=10128 COMPILER_WARMUP_BATCH_TOKENS=8192 ADAM_WD=0.0 RECURRENCE_START_FRACTION=0.65 RUN_ID=ablateC_legacy_wd000_r65 bash /workspace/run_god_tier_skc.sh >/workspace/logs/cuda/ablateC_legacy_wd000_r65.txt 2>&1 &
