#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "${ROOT_DIR}"

export RUN_ID="${RUN_ID:-depth3_from_start_$(date +%Y%m%d_%H%M%S)}"
export RECURRENCE_DEPTH="${RECURRENCE_DEPTH:-3}"
export TRAINING_DEPTH_RECURRENCE="${TRAINING_DEPTH_RECURRENCE:-3}"
export EVAL_DEPTH_RECURRENCE="${EVAL_DEPTH_RECURRENCE:-3}"
export RECURRENCE_START_FRACTION="${RECURRENCE_START_FRACTION:-0.0}"
export EVAL_HW_TIER="${EVAL_HW_TIER:-h100_8x}"
export FEEDBACK_PASSES="${FEEDBACK_PASSES:-1}"
export EVAL_FEEDBACK_PASSES="${EVAL_FEEDBACK_PASSES:-1}"
export TTT_GRAD_CHECKPOINT="${TTT_GRAD_CHECKPOINT:-0}"
export TTT_BATCH_SEQS="${TTT_BATCH_SEQS:-32}"
export TTT_CHUNK_TOKENS="${TTT_CHUNK_TOKENS:-32768}"
export RUN_TTT_SLIDING="${RUN_TTT_SLIDING:-0}"
export TORCHDYNAMO_CAPTURE_SCALAR_OUTPUTS="${TORCHDYNAMO_CAPTURE_SCALAR_OUTPUTS:-1}"
export TORCHDYNAMO_CACHE_SIZE_LIMIT="${TORCHDYNAMO_CACHE_SIZE_LIMIT:-64}"

exec "${ROOT_DIR}/run_god_tier_skc.sh"
